---
###############################
## Get Application ID       ###
###############################
    - name: Get App ID from Ravello
      local_action:
        module: ravello_get_id
        resource_type: applications
        resource_name: "{{ item.app_name }}"
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      register: apps
      run_once: true
      with_items: "{{ ravello_app_list }}"

###############################
##  Start the application   ##
###############################

    - name: Start all VMs in Application on Ravello
      local_action:
        module: uri
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ item.json.id }}/start"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 202
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
      run_once: true
      changed_when: true
      with_items: "{{ apps.results }}"

    - name: Set Application Expiration time
      local_action:
        module: uri
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ item.json.id }}/setExpiration"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: '{  "expirationFromNowSeconds": {{ ravello_expiration_time_min * 60 }} }'
        body_format: json
      run_once: true
      with_items: "{{ apps.results }}"
