---

###############################
## Get Application ID       ###
###############################
    - name: Get App ID from Ravello
      ravello_get_id:
        resource_name: "{{ ravello_app_name }}"
        resource_type: applications
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      register: app
      run_once: true
      tags: [ deploy, start ]

    # - debug: var=app
    #   run_once: true

###############################
##  Deploy the application   ##
###############################

    - name: Deploy Ravello Application
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ app.json.id }}/publish"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 202
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: >
          {
              "preferredCloud": "{{ ravello_deploy_topology_cloud }}",
              "preferredRegion": "{{ ravello_deploy_topology_region }}",
              "optimizationLevel": "{{ ravello_deploy_topology_optimization }}",
              "startAllVms": "{{ ravello_deploy_topology_start_all }}"
          }
        body_format: json
      run_once: true
      when: not app.json.published
      tags: [ deploy, start ]

########################################
##  Set application Expiration time   ##
########################################

    - name: Set Application Expiration time
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ app.json.id }}/setExpiration"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: '{  "expirationFromNowSeconds": {{ ravello_expiration_time_min * 60 }} }'
        body_format: json
      run_once: true
      when: not app.json.published
      tags: [ deploy, start ]

#################################
## Launch VMs one by one       ##
#################################
    - name: Get VM ID from Ravello
      ravello_get_vm:
        application_id: "{{ app.json.id }}"
        vm_name: "{{ inventory_hostname }}"
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      register: vm
      tags: [ start ]

#    - debug: var=vm
    - name: Start VM
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ app.json.id }}/vms/{{ vm.json.id }}/start"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 202
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
      changed_when: true
      tags: [ start ]
